name: Fetch Todo JSON

permissions: # ←⭐ 반드시 추가
  contents: write

on:
  push:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 커밋 히스토리 보존

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: pip install requests

      - run: python scripts/fetch_todo.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add test.json
          git commit -m "Auto-update test.json via GitHub Action" || echo "No changes"
          git push origin master
